### ISSUE TITLE
Update License in the Maven Repository from AGPL 3.0 to GPL 3.0 

### ISSUE THREAD

**Issue by msigmond** [dedis/scapegoat-scalafix#4]
I appreciate everyone's hard work, this is a great project.
I noticed that while the license in the GitHub project is GNU GENERAL PUBLIC LICENSE 3.0, the Maven repository is setup with GNU **Affero** General Public License 3.0.
I am wondering if this is intentional, and if it is not, would it be possible to update the Maven repository to GPL 3.0?

The driver is  that I would like to use scapegoat-scalafix at work, however the AGPL 3.0 license is blocked at my firm, while GPL 3.0 is permitted.
Please let me know.

**Comment by msigmond** [comment]
@t1b00 please could you advise on this?

**Comment by t1b00** [comment]
Hey, good catch, definetly not intentional! I'll publish an updated version during the day

**Comment by msigmond** [comment]
Much appreciated, @t1b00
